### ISSUE TITLE
Should take explicit reactor and thread pool arguments.

### ISSUE THREAD

**Issue by dreid** [rackerlabs/txkazoo#4]
If you make this always take an explicit reactor it'll be easier to test (without resorting `mock`) as well as it'll give the user of txkazoo more control over the thread pool to use.  

The most common construction probably looks like this:

```python
from twisted.internet import reactor
reactor.suggestThreadPoolSize(10)
kc = TxKazooClient(reactor, reactor.getThreadPool(), **kwargs)
```

But there are valid reasons a particular application would want to create a thread pool just for kazoo, which would look like:

```python
from twisted.internet import reactor, threads
threadPool = threads.ThreadPool(
    minthreads=10, 
    maxthreads=100, 
    name="zookeeper-threads"
)
kc = txKazooClient(reactor, threadPool, **kwargs)
```

**Comment by radix** [comment]
This is fixed in master.
